server:
  port: 9191

spring:
  application:
    name: gateway
      
zuul:
  routes:
    adder: 
      path: /one/**
    sub: 
      path: /two/**
      
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7171/eureka/    
        